class IOMailer::InputConverter
  
  #returns an array of lines
  def split_lines(text)
    res = text.split"\n"
    res = ["No Output was generated by the command!"] if res.length < 1
    res
  end
end